version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major"]
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
