name: Docker Image CI

on:
  push:
    branches: 
      - $default-branch
      - development
      - master
    tags:
      - '*.*.*-*'
  # Run tests for any PRs
  pull_request:

env:
  IMAGE_NAME: php74-fpm

jobs:
  lint-docker-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint dockerfile
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: Dockerfile
  build:
    needs:
      - lint-docker-file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_NAME}
    - name: Test the Docker image
      run: |
        CONTAINER_OUTPUT="$(docker run --rm -t ${IMAGE_NAME} -v)"
        TEST_STRING="$(echo "${CONTAINER_OUTPUT}" | grep -E '^PHP\s7\.4' | cut -d'.' -f3 --complement)"
        if ! [ "${TEST_STRING}" = "PHP 7.4" ]; then exit 1; fi
    - name: Test composer
      run: docker run -i ${IMAGE_NAME} composer --version || exit 1
    - name: Testing characters
      run: docker run -i ${IMAGE_NAME} php -r 'print (iconv("utf-8", "ASCII//TRANSLIT", "ströng contäning ümlaöits"));' || exit 1
